# ========================
# === Alacritty Colors ===
# ========================

# primary
[colors.primary]
background = "#1f1f1f"
foreground = "#a9a9a9"

# normal
[colors.normal]
black   = "#252525"
red     = "#d05c65"
green   = "#88b369"
yellow  = "#d5b06b"
blue    = "#519fdf"
magenta = "#b668cd"
cyan    = "#46a6b2"
white   = "#a9a9a9"

# bright
[colors.bright]
black   = "#474747"
red     = "#d05c65"
green   = "#88b369"
yellow  = "#d5b06b"
blue    = "#519fdf"
magenta = "#b668cd"
cyan    = "#46a6b2"
white   = "#a9a9a9"

# cursor
[colors.cursor]
cursor = "#a9a9a9"
text   = "#1f1f1f"

# selection
[colors.selection]
background = "#303030"
text       = "#a9a9a9"

# matches
[colors.search.matches]
background = "#d5b06b"
foreground = "#252525"

# focused match
[colors.search.focused_match]
background = "#d5b06b"
foreground = "#252525"
