# ==========================
# === Alacritty Settings ===
# ==========================

window:
  # preset dimensions
  dimensions:
    columns: 160
    lines:   48

  # window padding
  padding:
    x: 5
    y: 5

  # title
  title: Alacritty

  # meta key
  option_as_alt: OnlyLeft

env:
  # set colors
  TERM: xterm-256color

key_bindings:
  # create new window
  - { key: N, mods: Command, action: CreateNewWindow }
