# =========================
# === GitHub CLI Config ===
# =========================

# aliases
aliases:
    rl: repo list
    rv: repo view
    re: repo edit
    al: auth login
    rc: release create
    create: '!git create'

# preferred protocol
git_protocol: https
